// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/packets.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/packets.proto

It has these top-level messages:
	RequestSendEmail
	ResponseSendEmail
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestSendEmail struct {
	To   string `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	From string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	Body string `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
}

func (m *RequestSendEmail) Reset()                    { *m = RequestSendEmail{} }
func (m *RequestSendEmail) String() string            { return proto.CompactTextString(m) }
func (*RequestSendEmail) ProtoMessage()               {}
func (*RequestSendEmail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestSendEmail) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *RequestSendEmail) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *RequestSendEmail) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ResponseSendEmail struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ResponseSendEmail) Reset()                    { *m = ResponseSendEmail{} }
func (m *ResponseSendEmail) String() string            { return proto.CompactTextString(m) }
func (*ResponseSendEmail) ProtoMessage()               {}
func (*ResponseSendEmail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseSendEmail) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ResponseSendEmail) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestSendEmail)(nil), "pb.RequestSendEmail")
	proto.RegisterType((*ResponseSendEmail)(nil), "pb.ResponseSendEmail")
}

func init() { proto.RegisterFile("pb/packets.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x48, 0xd2, 0x2f,
	0x48, 0x4c, 0xce, 0x4e, 0x2d, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0xf2, 0xe2, 0x12, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x09, 0x4e, 0xcd, 0x4b, 0x71,
	0xcd, 0x4d, 0xcc, 0xcc, 0x11, 0xe2, 0xe3, 0x62, 0x2a, 0xc9, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x62, 0x2a, 0xc9, 0x17, 0x12, 0xe2, 0x62, 0x49, 0x2b, 0xca, 0xcf, 0x95, 0x60, 0x02, 0x8b,
	0x80, 0xd9, 0x20, 0xb1, 0xa4, 0xfc, 0x94, 0x4a, 0x09, 0x66, 0x88, 0x18, 0x88, 0xad, 0xe4, 0xc8,
	0x25, 0x18, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x8a, 0x30, 0x4c, 0x8c, 0x8b, 0xad, 0x28,
	0xb5, 0xb8, 0x34, 0xa7, 0x04, 0x6a, 0x20, 0x94, 0x27, 0x24, 0xc2, 0xc5, 0x9a, 0x5a, 0x54, 0x94,
	0x5f, 0x04, 0x35, 0x15, 0xc2, 0x49, 0x62, 0x03, 0xbb, 0xcc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x54, 0xfa, 0xe6, 0xfa, 0xad, 0x00, 0x00, 0x00,
}
